// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBsz1lbF1JaTEGgD1W0Bjf1m6iRHP8mW4',
    appId: '1:856037157116:android:7058e33fbfe76f0e88cf79',
    messagingSenderId: '856037157116',
    projectId: 'moviesapp-eea4b',
    databaseURL: 'https://moviesapp-eea4b-default-rtdb.firebaseio.com',
    storageBucket: 'moviesapp-eea4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4wd6H7HvpkQHNE-BxFt1_l50C-E0Sb6c',
    appId: '1:856037157116:ios:007f3757fd096aa888cf79',
    messagingSenderId: '856037157116',
    projectId: 'moviesapp-eea4b',
    databaseURL: 'https://moviesapp-eea4b-default-rtdb.firebaseio.com',
    storageBucket: 'moviesapp-eea4b.firebasestorage.app',
    iosClientId: '856037157116-b8mpfunnooj1krvuuk5e4fdvbu8cucf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
